# DirectoryPath, path to load train_dataset and test_dataset
DATA_PATH: ./data

# DirectoryPath, path to save models, components and results
MODEL_PATH: ./models

# DirectoryPath, path to save reports, mainly for html files that show history and forecast for each store
REPORT_PATH: ./reports

# Integer, or None. Max Store Count is used as a limiter for how many stores the mass forecaster will be run
# When commented out, left empty or set to null it defaults to run for all stores
MAX_STORE_COUNT:

# Boolean, Whether to include promotions in regression, defaults to True
INCLUDE_PROMO: True

# Boolean, Whether to include school holidays in regression, defaults to True
INCLUDE_HOLIDAY: True

# Dictionary, Parameter Grid to use in hyperparameter optimization, a default is included in src/config/config.py
PARAM_GRID:
  changepoint_prior_scale:
  - 0.001
  - 0.01
  - 0.1
  - 0.5
  seasonality_mode:
  - additive
  - multiplicative
  seasonality_prior_scale:
  - 0.01
  - 0.1
  - 1.0
  - 10.0